# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "main" ]
permissions:
  contents: read # Required for actions/checkout
  pull-requests: write # Required for gh bot to comment on PR

jobs:
  trivy-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true
          version: v0.58.1

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs' # filesystem scanner
          scan-ref: '.' # whole repo
          trivy-config: trivy.yaml # Use our config file
          skip-setup-trivy: true # We used the separate setup step to enable caching
        continue-on-error: true # By default, error would end the workflow

      - name: Report to PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('alpha/trivy-report.txt', 'utf8');
            const output = `Trivy report:
            \`\`\`\n
            ${report.length > 0 ? report : 'No issues found'}
            \`\`\`

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Trivy Status
        if: steps.trivy.outcome == 'failure'
        run: exit 1
        shell: bash


  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - run: mkdir -p subdir
    - run: echo '{}' > subdir/package-lock.json  # Ensure package-lock.json exists
    - uses: actions/setup-node@v3
      with:
#        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: ./subdir/package-lock.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
#        node-version-file: '.nvmrc'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./subdir/package-lock.json 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
